name: Daily Data Database Updater

on:
  schedule:
    # Runs exactly once a day at 17:30 UTC (23:00 Indian Standard Time)
    - cron: '00 23 * * *' #Minute, Hour, Day of the Month, Month, Day of Week
    # * represents null
  
  # Keeps a manual "Run workflow" button in your GitHub dashboard just in case
  workflow_dispatch:

jobs:
  execute-scripts:
    runs-on: ubuntu-latest

    steps:
      # 1. Pulls your code from your repository onto the GitHub runner machine
      - name: Checkout repository code
        uses: actions/checkout@v4

      # 2. Sets up a clean Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # 3. Installs the exact libraries your script needs to connect to CockroachDB
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 4. THE SPECIFIC MAIN CODE TO RUN YOUR FILE
      - name: Run NSE Daily Price Fetcher Script
        env:
          # This securely links your secret database password to your python script environment
          database_password_cockroach_db: ${{ secrets.DATABASE_PASSWORD_COCKROACH_DB }}
        run: |
          python -u "daily_fetcher_price.py"

      # Step 4: Your original script
      - name: Run NSE Daily Valuation Fetcher Script
        env:
          database_password_cockroach_db: ${{ secrets.DATABASE_PASSWORD_COCKROACH_DB }}
        run: |
          python -u "valuation_daily_fetcher.py"

      # Step 5: Your second script
      - name: Run India Vix Daily Data Fetcher Script
        env:
          database_password_cockroach_db: ${{ secrets.DATABASE_PASSWORD_COCKROACH_DB }}
        run: |
          python -u "india_vix_daily.py"

      # Step 6: Your third script
      - name: Run Advance Decline Daily Data Fetcher Script
        env:
          database_password_cockroach_db: ${{ secrets.DATABASE_PASSWORD_COCKROACH_DB }}
        run: |
          python -u "adv_dec_daily_fetcher.py"
